santon/apps/catalog/urls.py
from django.conf.urls import url

from santon.apps.catalog import views


urlpatterns = [
    url(
        r"^category/(?P<category_slug>[-\w]+)/",
        views.ProductListView.as_view(),
        name="category_list"
    ),
    url(
        r"^(?P<slug>[-\w]+)/$",
        views.ProductDetailView.as_view(),
        name="detail"
    ),

]

santon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

from santon import views


urlpatterns = [
    url(r"^$", views.IndexTemplateView.as_view(), name="index"),
    url(r"^services/$", views.ServicesTemplateView.as_view(), name="services"),
    url(r"^contact/$", views.ContactFormView.as_view(), name="contact"),
    url(
        r"^products/",
        include("santon.apps.catalog.urls", namespace="catalog")
    ),
    url(r'^news/', include('newsapp.urls')),
    url(r"^admin/", admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
]

urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )



if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

santon/apps/catalog/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models

from colorfield.fields import ColorField

from santon import utils
from santon.apps.category.models import Category
from santon.apps.gallery.models import Gallery
from santon.apps.seo.models import SEO


class Brand(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField()

    class Meta(object):
        ordering = ["name"]

    def __unicode__(self):
        return self.name


class Fabric(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name


class Colour(models.Model):
    name = models.CharField(max_length=50)
    colour = ColorField(default="#000000")

    def __unicode__(self):
        return self.name


class Size(models.Model):
    size = models.CharField(
        max_length=10, help_text="Use short name, e.g. XXL"
    )

    def __unicode__(self):
        return self.size


class Product(models.Model):
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=True)
    position = models.PositiveIntegerField(default=0)

    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    code = models.CharField(max_length=20, blank=True, null=True)
    blurb = models.TextField()

    weight = models.DecimalField(
        max_digits=5, decimal_places=2, blank=True, null=True
    )
    unit_of_weight = models.CharField(
        max_length=10,
        choices=utils.construct_choices(
            settings.SANTON_CONFIG["UNIT_OF_WEIGHT"]
        ), blank=True, null=True
    )
    fabric = models.ForeignKey(Fabric)
    brands = models.ManyToManyField(Brand)
    colours = models.ManyToManyField(Colour)
    sizes = models.ManyToManyField(Size)

    categories = models.ManyToManyField(Category)
    gallery = models.ForeignKey(Gallery, blank=True, null=True)

    seo = GenericRelation(SEO)

    class Meta(object):
        ordering = ["position"]

    def __unicode__(self):
        return self.name

    @property
    def size_str(self):
        return ", ".join(size.size for size in self.sizes.all())

    @property
    def brand_str(self):
        return ", ".join(brand.name for brand in self.brands.all())

    @property
    def thumbnail(self):
        try:
            return getattr(self.gallery.images.first(), "image", None)
        except AttributeError:
            pass

santon/apps/category/models.py
from __future__ import unicode_literals

from django.db import models


class Category(models.Model):
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    featured = models.BooleanField(default=False)

    class Meta(object):
        verbose_name_plural = "Categories"

    def __unicode__(self):
        return self.name

santon/apps/download/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

santon/apps/gallery/models.py
from __future__ import unicode_literals

from django.db import models


class Gallery(models.Model):
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=True)

    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)

    class Meta(object):
        verbose_name_plural = "Galleries"

    def __unicode__(self):
        return self.name


class Image(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="uploads/%Y/%m/")
    gallery = models.ForeignKey(
        Gallery, related_name="images", blank=True, null=True
    )

santon/apps/seo/models.py
from __future__ import unicode_literals

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models


class SEO(models.Model):
    """
    A simple SEO model which points to a generic foreign key.
    """
    title = models.CharField(max_length=55)
    description = models.CharField(max_length=160)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    class Meta(object):
        verbose_name = "SEO"
        verbose_name_plural = "SEO"

    def __unicode__(self):
        return self.title

santon/forms.py
from django import forms

from santon.utils import construct_choices, render_email_template, send_email


class ContactForm(forms.Form):
    full_name = forms.CharField(
        max_length=150,
        widget=forms.widgets.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    contact_number = forms.CharField(
        max_length=15,
        widget=forms.widgets.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    email_address = forms.EmailField(widget=forms.widgets.TextInput(
        attrs={
            "class": "form-control"
        }
    ))
    closest_branch = forms.CharField(
        widget=forms.widgets.Select(
            choices=construct_choices(["Johannesburg", "Durban"])
        )
    )
    message = forms.CharField(max_length=1000, widget=forms.widgets.Textarea(
        attrs={
            "class": "form-control"
        }
    ))

    newsletter = forms.BooleanField(
        initial=True, label='I want to receive more news and updates from Santon Workwear'
    )

    def send_email(self):
        data = self.cleaned_data
        send_email(
            "[SANTON] Website Enquiry",
            render_email_template(
                "santon/emails/enquiry.txt", {
                    "data": data
                }
            ),
            to=["jhbsales@santonworkwear.co.za"],
            reply_to=["%s <%s>" % (data["full_name"], data["email_address"])]
        )

santon/apps/catalog/views.py
from django.views.generic import DetailView, ListView

from santon.apps.catalog.models import Product


class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        queryset = super(
            ProductListView, self
        ).get_queryset().filter(published=True)

        category_slug = self.kwargs.get("category_slug")
        if category_slug is not None:
            queryset = queryset.filter(categories__slug=category_slug)
        return queryset


class ProductDetailView(DetailView):
    model = Product

    def get_queryset(self):
        return super(
            ProductDetailView, self
        ).get_queryset().filter(published=True)

santon/apps/category/views.py
from django.shortcuts import render

# Create your views here.

santon/apps/download/views.py
from django.shortcuts import render

# Create your views here.

santon/apps/gallery/views.py
from django.shortcuts import render

# Create your views here.

santon/apps/seo/views.py
from django.shortcuts import render

# Create your views here.

santon/views.py
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView
from django.template.response import TemplateResponse

from santon.forms import ContactForm


class IndexTemplateView(TemplateView):
    template_name = "santon/index.html"


class ServicesTemplateView(TemplateView):
    template_name = "santon/services.html"


class ContactFormView(FormView):
    form_class = ContactForm
    template_name = "santon/contact.html"
    success_url = reverse_lazy("contact")

    def form_valid(self, form):
        form.send_email()
        return TemplateResponse(
            self.request, self.template_name, {"success": True}
        )

santon/templates/santon/contact.html
{% extends "base.html" %}

{% load static catalog_tags %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h1>Get In Contact With Us</h1></div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <h3>Branches </h3>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Durban </h3></div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-12">
                                    <iframe allowfullscreen="" frameborder="0" width="100%" height="100" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyB3EL1MqPIqn1H_PzyoTNN8LVRkNbEV80k&amp;q=26+Anderson+Rd,+Elangeni,+Mpumalanga&amp;zoom=15"></iframe>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-2"><i class="glyphicon glyphicon-earphone"></i></div>
                                <div class="col-md-10">
                                    <p class="paragraph-feature-description">031 569 6106 </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-2"><i class="glyphicon glyphicon-map-marker"></i></div>
                                <div class="col-md-10">
                                    <p class="paragraph-feature-description">
                                        Unit 16 Spurwing Industrial Park,
                                        <br>26 Anderson Road
                                        <br>Hammarsdale
                                        <br>KZN
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Johannesburg </h3></div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-12">
                                    <iframe allowfullscreen="" frameborder="0" width="100%" height="100" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyB3EL1MqPIqn1H_PzyoTNN8LVRkNbEV80k&amp;q=Santon+Workwear%2C+Strijdom+Park&amp;zoom=15"></iframe>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-2"><i class="glyphicon glyphicon-earphone"></i></div>
                                <div class="col-md-10">
                                    <p class="paragraph-feature-description">011 791 0919 </p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-2"><i class="glyphicon glyphicon-map-marker"></i></div>
                                <div class="col-md-10">
                                    <p class="paragraph-feature-description">
                                        Unit B, Hi-Tech Industrial Park,
                                        <br>14-16 Gerhardus Street,
                                        <br>Strijdom Park,
                                        <br>Johannesburg
                                        <br>Gauteng
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <h3>Contact Form</h3>
            {% if success %}
                <p>Thank you for getting in contact with us. We will get back to as soon as possible.</p>
            {% else %}
                <p>Please complete the form below to get in contact with us.</p>
                <div class="column-spacer-30"></div>
                <form class="form-horizontal" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="col-sm-4">
                            <label class="control-label">FULL NAME</label>
                        </div>
                        <div class="col-sm-8">
                            {{ form.full_name }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-4">
                            <label class="control-label">CONTACT NUMBER</label>
                        </div>
                        <div class="col-sm-8">
                            {{ form.contact_number }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-4">
                            <label class="control-label">EMAIL ADDRESS</label>
                        </div>
                        <div class="col-sm-8">
                            {{ form.email_address }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-4">
                            <label class="control-label">CLOSEST BRANCH</label>
                        </div>
                        <div class="col-sm-8">
                            {{ form.closest_branch }}
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-4">
                            <label class="control-label">MESSAGE </label>
                        </div>
                        <div class="col-sm-8">
                            {{ form.message }}
                        </div>
               
                    </div>
                    <div class="form-group">

                        <div class="col-sm-8">
                            <label class="control-label">I want to receive more news and updates from Santon Workwear </label>
                        </div>

                        <div class="col-sm-4 text-right">
                            {{ form.newsletter }}
                        </div>                
                    </div>
                    <div class="form-group">
                        <div class="col-sm-12">
                            <button class="btn btn-default float-right" type="submit">Submit</button>
                        </div>
                    </div>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock content %}

santon/templates/santon/index.html
{% extends "base.html" %}

{% load static catalog_tags santon_tags %}

{% block content %}
    <div class="col-md-8">
        <h1>Welcome to Santon Workwear</h1>
        <p>Santon Workwear is a South African based leading manufacturer of workwear and overalls. With over 20 years’ experience in the industry we
            constantly endeavor and pursue our original company motto of "Quality and Service"</p>
        <p>Our team of qualified quality experts put careful consideration in the design and function of each and every style of garment Santon Workwear
            manufactures. Our buyers also only source the best quality fabrics and trims that make up our garments to ensure lasting longevity of each and
            every item that is made.</p>
        <p class="hidden-xs">We pride ourselves on not only providing high quality workwear to all markets, but that we employ and train local South Africans to do so.
            Established in 1995, we have grown into a competitive company, manufacturing over 3500 garments per day in our Hammarsdale factory, employing
            approx. 280 people.</p>
        <p class="hidden-xs">Our company is SABS approved under the Endurance Workwear banner and under the brand we have the ability to supply smaller subcontractors to
            large mining companies to parastatals.</p>
        <p class="hidden-xs">Together with manufacturing workwear, we are also distributors for many different safety footwear brands, namely Kaliber, Bova, Lemaitre, Frams
            and Wayne. We also stock various PPE accessories such as t-shirts, golf shirts, rainwear and Hi-Viz clothing. We offer in-house screenprinting
            and embroidery to supply a fully branded product to the customer.</p>
        </div>
    <div class="col-md-4">
        {% get_catalog_category_list featured=1 as category_list %}
        {% for category in category_list %}
            {% get_first_product category_slug=category.slug as product %}
            <div class="media">
                <div class="media-left">
                    <a href="{% url "catalog:category_list" category.slug %}"><img src="{% resize_image product.thumbnail 100 100 %}" width="100" height="100"></a>
                </div>
                <div class="media-body">
                    <h4>{{ category.name }}</h4>
                    <p>
                        <a href="{% url "catalog:category_list" category.slug %}" class="btn btn-default btn-small" type="button">Learn more</a>
                    </p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

santon/templates/santon/services.html
{% extends "base.html" %}

{% load static catalog_tags %}

{% block content %}
    <div class="col-md-12">
        <h1>Our Services</h1>
        <div class="media">
            <div class="media-left">
                <a><img src="{% static "img/service-001.jpg" %}" width="120"></a>
            </div>
            <div class="media-body">
                <h4>Embroidery </h4>
                <p>If embroidery is required, please send us your logo and we can cost individually to your requirements, embroidered logos are long lasting and
                    extremely neat but can be slightly more expensive than screenprinting. Logos can be placed anywhere on the garments and there are no colour
                    minimums necessary. All logos will be digitized and sampled and sent to our customers for approval before applying them onto the garments.</p>
            </div>
        </div>
        <div class="media">
            <div class="media-left">
                <a><img src="{% static "img/service-002.jpg" %}" width="120"></a>
            </div>
            <div class="media-body">
                <h4>Manufacturing </h4>
                <p>Santon Workwear manufactures all overalls and workwear in our Hammarsdale factory in KZN. We do not import any made up overall. That
                    being so, as a customer you are dealing with a factory and as a factory we require minimums in order to manufacture non stock items.
                    Minimums of 100 units per colour per style are required to run special order through the factory. All stock items can be placed as and
                    when you require and we will not force you to buy boxed lots.</p>
            </div>
        </div>
        <div class="media">
            <div class="media-left">
                <a><img src="{% static "img/service-003.jpg" %}" width="120"></a>
            </div>
            <div class="media-body">
                <h4>Screenprinting </h4>
                <p>We operate our own in-house screenprinting room and can print up to 6 colour logos. All logos are digitized and approved with our clients
                    before applying them onto the garments.</p>
            </div>
        </div>
    </div>
    </div>
{% endblock content %}