santon/apps/catalog/urls.py
from django.conf.urls import url

from santon.apps.catalog import views


urlpatterns = [
    url(
        r"^category/(?P<category_slug>[-\w]+)/",
        views.ProductListView.as_view(),
        name="category_list"
    ),
    url(
        r"^(?P<slug>[-\w]+)/$",
        views.ProductDetailView.as_view(),
        name="detail"
    ),

]

santon/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

from santon import views


urlpatterns = [
    url(r"^$", views.IndexTemplateView.as_view(), name="index"),
    url(r"^services/$", views.ServicesTemplateView.as_view(), name="services"),
    url(r"^contact/$", views.ContactFormView.as_view(), name="contact"),
    url(
        r"^products/",
        include("santon.apps.catalog.urls", namespace="catalog")
    ),
    url(r'^news/', include('newsapp.urls')),
    url(r"^admin/", admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
]

urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )



if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

santon/apps/catalog/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models

from colorfield.fields import ColorField

from santon import utils
from santon.apps.category.models import Category
from santon.apps.gallery.models import Gallery
from santon.apps.seo.models import SEO


class Brand(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField()

    class Meta(object):
        ordering = ["name"]

    def __unicode__(self):
        return self.name


class Fabric(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name


class Colour(models.Model):
    name = models.CharField(max_length=50)
    colour = ColorField(default="#000000")

    def __unicode__(self):
        return self.name


class Size(models.Model):
    size = models.CharField(
        max_length=10, help_text="Use short name, e.g. XXL"
    )

    def __unicode__(self):
        return self.size


class Product(models.Model):
    date_added = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=True)
    position = models.PositiveIntegerField(default=0)

    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    code = models.CharField(max_length=20, blank=True, null=True)
    blurb = models.TextField()

    weight = models.DecimalField(
        max_digits=5, decimal_places=2, blank=True, null=True
    )
    unit_of_weight = models.CharField(
        max_length=10,
        choices=utils.construct_choices(
            settings.SANTON_CONFIG["UNIT_OF_WEIGHT"]
        ), blank=True, null=True
    )
    fabric = models.ForeignKey(Fabric)
    brands = models.ManyToManyField(Brand)
    colours = models.ManyToManyField(Colour)
    sizes = models.ManyToManyField(Size)

    categories = models.ManyToManyField(Category)
    gallery = models.ForeignKey(Gallery, blank=True, null=True)

    seo = GenericRelation(SEO)

    class Meta(object):
        ordering = ["position"]

    def __unicode__(self):
        return self.name

    @property
    def size_str(self):
        return ", ".join(size.size for size in self.sizes.all())

    @property
    def brand_str(self):
        return ", ".join(brand.name for brand in self.brands.all())

    @property
    def thumbnail(self):
        try:
            return getattr(self.gallery.images.first(), "image", None)
        except AttributeError:
            pass

santon/apps/catalog/views.py
from django.views.generic import DetailView, ListView

from santon.apps.catalog.models import Product


class ProductListView(ListView):
    model = Product

    def get_queryset(self):
        queryset = super(
            ProductListView, self
        ).get_queryset().filter(published=True)

        category_slug = self.kwargs.get("category_slug")
        if category_slug is not None:
            queryset = queryset.filter(categories__slug=category_slug)
        return queryset


class ProductDetailView(DetailView):
    model = Product

    def get_queryset(self):
        return super(
            ProductDetailView, self
        ).get_queryset().filter(published=True)

santon/apps/catalog/templates/catalog/product_detail.html
{% extends "base.html" %}

{% load catalog_tags santon_tags %}

{% block seo_title %}{{ object.seo.first.title|default:object.name }}{% endblock seo_title %}
{% block seo_description %}{{ object.seo.first.description|default:object.blurb|striptags|truncatewords:15 }}{% endblock seo_description %}

{% block content %}
    <div class="row row-content">
        <div class="col-md-12">
            <h1>{{ object.name }}</h1></div>
    </div>
    <div class="row row-content">
        <div class="col-md-4">
            {% for image in object.gallery.images.all %}
                {% if forloop.first %}
                    <img class="js-img-enlarge-container" src="{% resize_image image.image 300 300 %}" width="300">
                {% endif %}
                <a class="js-img-enlarge" href="{% resize_image image.image 300 300 %}"><img src="{% resize_image image.image 100 100 %}" width="100"></a>
            {% endfor %}
        </div>
        <div class="col-md-8">
            <div class="row">
                <div class="col-md-12">
                    <p class="paragraph-product-description">{{ object.blurb|default:"No description"|linebreaks }}</p>
                </div>
                <div class="col-md-12 column-spacer-30">
                    <div class="clearfix"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-3">
                            <p class="text-uppercase paragraph-feature-label">BRAND </p>
                        </div>
                        <div class="col-md-9">
                            <p class="paragraph-feature-description">{{ object.brand_str }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <p class="text-uppercase paragraph-feature-label">FABRIC </p>
                        </div>
                        <div class="col-md-9">
                            <p class="paragraph-feature-description">{{ object.fabric }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <p class="text-uppercase paragraph-feature-label">WEIGHT </p>
                        </div>
                        <div class="col-md-9">
                            <p class="paragraph-feature-description">{{ object.weight }} {{ object.unit_of_weight }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <p class="text-uppercase paragraph-feature-label">Sizes </p>
                        </div>
                        <div class="col-md-9">
                            <p class="paragraph-feature-description">{{ object.size_str }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <p class="text-uppercase paragraph-feature-label">Colours</p>
                        </div>
                        <div class="col-md-9">
                            {% for colour in object.colours.all %}
                                <div class="float-left div-colour-box" data-toggle="tooltip" data-placement="bottom" style="background-color:{{ colour.colour }};" title="{{ colour.name }}"></div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row row-content">
        <div class="col-md-12">
            <h3>Related Products</h3></div>
    </div>
    <div class="row row-content">
        {% get_related_products object as related_products %}

        {% for related_product in related_products %}
            <div class="col-md-3">
                <div class="media">
                    <div class="media-left">
                        <a href="{% url "catalog:detail" related_product.slug %}"><img src="{% resize_image related_product.thumbnail 100 100 %}" width="100"></a>
                    </div>
                    <div class="media-body">
                        <h4>{{ related_product.name }}</h4>
                        <p>
                            <a href="{% url "catalog:detail" related_product.slug %}" class="btn btn-default btn-small" type="button">Learn more</a>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

santon/apps/catalog/templates/catalog/product_list.html
{% extends "base.html" %}

{% load santon_tags %}

{% block content %}
    <div class="row row-content">
        <div class="col-md-12">
            <h1>Product Catalog</h1>
        </div>
    </div>
    <div class="row row-content">
        {% for object in object_list %}
            <div class="col-md-3">
                <div class="media">
                    <div class="media-left">
                        <a href="{% url "catalog:detail" object.slug %}"><img src="{% resize_image object.thumbnail 150 150 %}" width="100" height="100"></a>
                    </div>
                    <div class="media-body">
                        <h4>{{ object.name|title }}</h4>
                        <p>
                            <a href="{% url "catalog:detail" object.slug %}" class="btn btn-default btn-small" type="button">Learn more</a>
                        </p>
                    </div>
                </div>
            </div>
            {% if forloop.counter|divisibleby:4 or forloop.last %}
                </div>
                <div class="row row-content">
            {% endif %}
        {% endfor %}
    </div>
{% endblock content %}